version: '3.8'

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      # Option A: auto-create via env var
      MYSQL_DATABASE: order_service
      # Option B: you can still use init.sql if you need more complex setup
    ports:
      - "3307:3306"
    volumes:
      -  ./mysql:/var/lib/mysql
      -  ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
